api = 2
core = 7.x

; Common Modules
projects[animate_css][version] = "1.42"
projects[backup_migrate][version] = "3.9"
; dont forget to git clone https://github.com/tpyo/amazon-s3-php-class.git s3-php5-curl
projects[block_class][version] = "2.4"
projects[breadcrumbs_by_path][version] = "1.0-alpha13"
projects[breakpoints][version] = "1.6"
projects[captcha] = "1.7"
projects[ckeditor][version] = "1.22"
projects[ckeditor_plain_summary][version] = "1.0"
projects[ctools][version] = "1.19"
projects[date][version] = "2.12"
projects[entity][version] = "1.10"
projects[entity_rules][version] = "1.0-alpha4"
projects[entity2text][version] = "1.x-dev"
projects[entityform][version] = "2.0-rc4"
projects[entityreference][version] = "1.5"
projects[facetapi][version] = "1.6"
projects[feeds_tamper][version] = "1.2"
projects[feeds][version] = "2.0-beta5"
projects[fences][version] = "1.2"
projects[file_entity][version] = "3.0-beta19"
projects[field_default_token][version] = "1.3"
projects[filefield_sources][version] = "1.11"
projects[field_formatter_class][version] = "1.2"
projects[field_formatter_settings][version] = "1.1"
projects[field_group][version] = "1.6"
projects[field_hidden][version] = "1.8"
projects[field_validation][version] = "2.6"
projects[flexslider][version] = "2.0-rc2"
projects[floating_block][version] = "1.3"
projects[fontawesome][version] = "3.13"
projects[google_tag][version] = "2.x-dev"
projects[httpbl][version] = "1.0"
projects[i18n][version] = "1.31"
projects[i18n_contrib][version] = "1.0-alpha2"
projects[i18nviews][version] = "3.0-alpha1"
projects[l10n_update][version] = "2.6"
projects[jquery_dollar][version] = "1.1"
projects[jquery_update][version] = "3.0-alpha5"
projects[lang_dropdown][version] = "2.7"
projects[libraries][version] = "2.5"
projects[linkit][version] = "3.6"
projects[login_security][version] = "1.9"
projects[masonry_views][version] = "3.0"
projects[masonry][version] = "3.0-beta1"
projects[media_ckeditor][version] = "2.14"
projects[media][version] = "4.x-dev"
projects[metatag][version] = "1.28"
projects[module_filter][version] = "2.2"
projects[navbar][version] = "1.7"
projects[pathauto][version] = "1.3"
projects[picture][version] = "2.13"
projects[rabbit_hole][version] = "2.26"
projects[recaptcha][version] = "2.3"
projects[recaptcha_v3][version] = "1.0-alpha5"
projects[redirect][version] = "2.x-dev"
projects[remote_file_source][version] = "1.0"
projects[remote_stream_wrapper][version] = "1.0"
projects[rrssb][version] = "2.3"
projects[rules][version] = "2.12"
projects[search_api][version] = "1.28"
projects[search_api_autocomplete][version] = "1.7"
projects[search_api_attachments][version] = "1.19"
projects[search_api_db][version] = "1.8"
projects[search_api_page][version] = "1.6"
projects[search_api_solr][version] = "1.15"
projects[seckit][version] = "1.11"
projects[token_filter][version] = "1.1"
projects[token][version] = "1.8"
projects[tmgmt][version] = "1.0-rc3"
projects[tvi][version] = "1.0"
projects[views][version] = "3.25"
projects[views_data_export] = "3.2"
projects[views_bulk_operations][version] = "3.6"
projects[workflow][version] = "2.13"
projects[xmlsitemap][version] = "2.6"
projects[wowjs][version] = "1.2"

; Custom Modules
projects[location][download][type] = "git"
projects[location][download][url] = "https://github.com/lhaithaes/location.git"
projects[location][type] = "module"
projects[location][directory_name] = "location"

projects[features][type] = "module"
projects[features][download][type] = "git"
projects[features][download][url] = "https://github.com/Coulton7/features.git"

projects[social_content][type] = "module"
projects[social_content][download][type] = "git"
projects[social_content][download][url] = "https://github.com/Coulton7/social_content.git"

; Common Themes
projects[bootstrap][version] = "3.26"
projects[adminimal_theme][version] = "1.26"

projects[aesbs337][download][type] = "git"
projects[aesbs337][download][url] = "https://github.com/Coulton7/aesbs337.git"
projects[aesbs337][type] = "theme"
projects[aesbs337][directory_name] = "aesbs337"

projects[aesseal_classic][download][type] = "git"
projects[aesseal_classic][download][url] = "https://github.com/Coulton7/aesseal_classic.git"
projects[aesseal_classic][type] = "theme"
projects[aesseal_classic][directory_name] = "aesseal_classic"

; Libraries
libraries[animate][download][type] = "git"
libraries[animate][download][url] = "https://github.com/animate-css/animate.css.git"
libraries[animate][directory_name] = "animate"
libraries[animate][type] = "library"

libraries[backbone][download][type] = "get"
libraries[backbone][download][url] = "https://github.com/jashkenas/backbone/archive/1.1.0.zip"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[imagesloaded][download][type] = "get"
libraries[imagesloaded][download][url] = "https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"

libraries[imagesloaded][directory_name] = "imagesloaded"
libraries[imagesloaded][type] = "library"

libraries[masonry][download][type] = "file"
libraries[masonry][download][url] = "https://npmcdn.com/masonry-layout@3.3.2/dist/masonry.pkgd.min.js"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "https://raw.githubusercontent.com/BrianGilbert/modernizer-navbar/2.7.1/modernizr-min.js"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

libraries[rrssb][download][type] = "git"
libraries[rrssb][download][url] = "https://github.com/kni-labs/rrssb.git"
libraries[rrssb][directory_name] = "rrssb"
libraries[rrssb][type] = "library"

libraries[rrssb-plus][download][type] = "git"
libraries[rrssb-plus][download][url] = "https://github.com/AdamPS/rrssb-plus.git"
libraries[rrssb-plus][directory_name] = "rrssb-plus"
libraries[rrssb-plus][type] = "library"

libraries[underscore][download][type] = "get"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore/archive/1.5.2.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

libraries[wow][download][type] = "get"
libraries[wow][download][url] = "https://github.com/matthieua/WOW/archive/master.zip"
libraries[wow][directory_name] = "wow"
libraries[wow][type] = "library"

libraries[easing][download][type] = "get"
libraries[easing][download][url] = "https://github.com/gdsmith/jquery.easing/archive/master.zip"
libraries[easing][directory_name] = "easing"
libraries[easing][type] = "library"

libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woocommerce/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"
