; Common Modules
projects[backup_migrate][version] = "3.x-dev"
projects[block_class][version] = "2.4"
projects[breadcrumbs_by_path][version] = "1.0-alpha13"
projects[ckeditor_plain_summary][version] = "1.0"
projects[ctools][version] = "1.15"
projects[date][version] = "2.10"
projects[entity][version] = "1.9"
projects[entity_rules][version] = "1.0-alpha4"
projects[entity2text][version] = "1.x-dev"
projects[entityform][version] = "2.0-rc4"
projects[entityreference][version] = "1.5"
projects[fences][version] = "1.2"
projects[field_default_token][version] = "1.3"
projects[field_formatter_class][version] = "1.2"
projects[field_formatter_settings][version] = "1.1"
projects[field_group][version] = "1.6"
projects[field_validation][version] = "2.6"
projects[fontawesome][version] = "3.12"
projects[google_tag][version] = "2.x-dev"
projects[httpbl][version] = "1.0"
projects[image_class][version] = "1.0"
projects[jquery_dollar][version] = "1.1"
projects[jquery_update][version] = "3.0-alpha5"
projects[libraries][version] = "2.5"
projects[linkit][version] = "3.5"
projects[login_security][version] = "1.9"
projects[masonry_views][version] = "3.0"
projects[masonry][version] = "3.0-beta1"
projects[media_ckeditor][version] = "2.10"
projects[media][version] = "4.x-dev"
projects[metatag][version] = "1.27"
projects[module_filter][version] = "2.2"
projects[navbar][version] = "1.7"
projects[node_class][version] = "1.3"
projects[pathauto][version] = "1.3"
projects[picture][version] = "2.13"
projects[prepopulate][version] = "2.1"
projects[rabbit_hole][version] = "2.25"
projects[redirect][version] = "2.x-dev"
projects[remote_stream_wrapper][version] = "1.0"
projects[rrssb][version] = "2.3"
projects[rules][version] = "2.12"
projects[search_api_db][version] = "1.7"
projects[search_api_solr][version] = "1.15"
projects[search_api][version] = "1.26"
projects[site_map][version] = "1.3"
projects[title][version] = "1.0-beta3"
projects[token_filter][version] = "1.1"
projects[token][version] = "1.7"
projects[tvi][version] = "1.0"
projects[views_bulk_operations][version] = "3.5"
projects[views][version] = "3.24"
projects[xmlsitemap][version] = "2.6"

; Custom Modules
projects[location][download][type] = "git"
projects[location][download][url] = "https://github.com/lhaithaes/location.git"
projects[location][type] = "module"
projects[location][directory_name] = "location"

projects[globalredirect][version] = "1.6"
; See https://www.drupal.org/project/globalredirect/issues/2027705#comment-12700414
projects[globalredirect][patch][] = https://www.drupal.org/files/issues/conflict_between_global-2027705-13.patch

projects[ckeditor][type] = "module"
projects[ckeditor][download][type] = "get"
projects[ckeditor][download][url] = "https://s3-eu-west-1.amazonaws.com/aesweb/sites/all/libraries/ckeditor.tar.gz"

projects[features][type] = "module"
projects[features][download][type] = "git"
projects[features][download][url] = "https://github.com/Coulton7/features.git"

projects[social_content][type] = "module"
projects[social_content][download][type] = "git"
projects[social_content][download][url] = "https://github.com/Coulton7/social_content.git"

; Common Themes
projects[bootstrap][version] = "3.23"
projects[adminimal_theme][version] = "1.25"

projects[aesbs337][download][type] = "git"
projects[aesbs337][download][url] = "https://github.com/Coulton7/aesbs337.git"
projects[aesbs337][type] = "theme"
projects[aesbs337][directory_name] = "aesbs337"

projects[aesseal_classic][download][type] = "git"
projects[aesseal_classic][download][url] = "https://github.com/Coulton7/aesseal_classic.git"
projects[aesseal_classic][type] = "theme"
projects[aesseal_classic][directory_name] = "aesseal_classic"

; Libraries
libraries[animate][download][type] = "get"
libraries[animate][download][url] = "https://github.com/daneden/animate.css/archive/master.zip"
libraries[animate][directory_name] = "animate"
libraries[animate][type] = "library"

libraries[backbone][download][type] = "get"
libraries[backbone][download][url] = "https://github.com/jashkenas/backbone/archive/1.1.0.zip"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[imagesloaded][download][type] = "get"
libraries[imagesloaded][download][url] = "http://desandro.github.io/imagesloaded/imagesloaded.pkgd.min.js"
libraries[imagesloaded][directory_name] = "imagesloaded"
libraries[imagesloaded][type] = "library"

libraries[masonry][download][type] = "file"
libraries[masonry][download][url] = "https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "https://raw.githubusercontent.com/BrianGilbert/modernizer-navbar/2.7.1/modernizr-min.js"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

libraries[rrssb][download][type] = "git"
libraries[rrssb][download][url] = "https://github.com/kni-labs/rrssb.git"
libraries[rrssb][directory_name] = "rrssb"
libraries[rrssb][type] = "library"

libraries[rrssb-plus][download][type] = "git"
libraries[rrssb-plus][download][url] = "https://github.com/AdamPS/rrssb-plus.git"
libraries[rrssb-plus][directory_name] = "rrssb-plus"
libraries[rrssb-plus][type] = "library"

libraries[underscore][download][type] = "get"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore/archive/1.5.2.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

libraries[wow][download][type] = "get"
libraries[wow][download][url] = "https://github.com/matthieua/WOW/archive/master.zip"
libraries[wow][directory_name] = "wow"
libraries[wow][type] = "library"

libraries[easing][download][type] = "get"
libraries[easing][download][url] = "https://github.com/gdsmith/jquery.easing/archive/master.zip"
libraries[easing][directory_name] = "easing"
libraries[easing][type] = "library"
