api = 2
core = 7.x

; Drupal 7
projects[drupal][type] = "core"
projects[drupal][download][type] = "get"
projects[drupal][download][url] = "https://github.com/omega8cc/7x/archive/7.59.1.tar.gz"

; Modules
projects[ajax_facets][version] = "3.7"
projects[backup_migrate][version] = "3.5"
projects[better_exposed_filters][version] = "3.5"
projects[block_class][version] = "2.3"
projects[breadcrumbs_by_path][version] = "1.0-alpha13"
projects[bu][version] = "1.4"
projects[ctools][version] = "1.14"
projects[chosen][version] = "2.1"
projects[conditional_fields][version] = "3.0-alpha2"
projects[context][version] = "3.7"
projects[context_layouts][version] = "3.7
projects[current_search][version] = "1.5"
projects[search_api_db][version] = "1.6"
projects[ds][version] = "2.14"
projects[ds_bootstrap_layouts][version] = "3.1"
projects[ds_ui][version] = "2.14"
projects[entity][version] = "1.9"
projects[entityconnect][version] = "1.0-rc4"
projects[entityreference][version] = "1.5"
projects[entityreference_behavior_example][version] = "1.5"
projects[entity_rules][version] = "1.0-alpha4"
projects[entity2text][version] = "1.0-alpha3"
projects[entity_token][version] = "1.9"
projects[entityform][version] = "2.0-rc4"
projects[entityform_notifications][version] = "2.0-rc4"
projects[facetapi][version] = "1.5"
projects[facetapi_select][version] = "1.3+1-dev"
projects[fancy_file_delete][version] = "1.0-beta11"
projects[feeds][version] = "2.0-beta4"
projects[feeds_ui][version] = "2.0-beta4"
projects[feeds_import][version] = "2.0-beta4"
projects[feeds_tamper][version] = "1.2"
projects[feeds_tamper_ui][version] = "1.2"
projects[field_default_token][version] = "1.3"
projects[field_formatter_class][version] = "1.1"
projects[field_formatter_settings][version] = "1.1"
projects[field_group][version] = "1.6"
projects[field_group_multiple][version] = "1.0-beta3"
projects[field_validation][version] = "2.6"
projects[file_entity][version] = "2.16"
projects[filefield_sources][version] = "1.11"
projects[globalredirect][version] = "1.6"
projects[googleanalytics][version] = "2.4"
projects[httpbl][version] = "1.0"
projects[imageblock][version] = "1.3"
projects[image_field_caption][version] = "2.2"
projects[image_link_formatter][version] = "1.1"
projects[image_url_formatter][version] = "1.4"
projects[imagezoomer][version] = "1.0"
projects[job_scheduler][version] = "2.0"
projects[jquery_dollar][version] = "1.1"
projects[jquery_update][version] = "3.0-alpha5"
projects[libraries][version] = "2.3"
projects[link][version] = "1.4"
projects[login_security][version] = "1.9"
projects[media][version] = "2.16"
projects[media_feeds][version] = "2.0-alpha1"
projects[menu_attributes][version] = "1.0"
projects[menu_block][version] = "2.7"
projects[menu_views][version] = "2.5"
projects[metatag][version] = "1.22"
projects[metatag_context][version] = "1.22"
projects[metatag_views][version] = "1.22"
projects[module_filter][version] = "2.1"
projects[navbar][version] = "1.7"
projects[password_policy][version] = "1.15"
projects[pathauto][version] = "1.2"
projects[redirect][version] = "1.0-rc3"
projects[remote_file_source][version] = "1.0"
projects[remote_stream_wrapper][version] = "1.0-rc1"
projects[respondjs][version] = "1.5"
projects[rules][version] = "2.10"
projects[rules_admin][version] = "2.10"
projects[search_api][version] = "1.21"
projects[search_api_autocomplete][version] = "1.4"
projects[search_api_exclude][version] = "1.2"
projects[search_api_facetapi][version] = "1.21"
projects[search_api_views][version] = "1.21"
projects[sharethis][version] = "2.12"
projects[shs][version] = "1.7"
projects[search_api_solr][version] = "1.12"
projects[tablefield][version] = "2.4"
projects[taxonomy_menu][version] = "1.5"
projects[textformatter][version] = "1.4"
projects[token][version] = "1.7"
projects[views][version] = "3.18"
projects[views_bulk_operations][version] = "3.4"
projects[views_data_export][version] = "3.2"
projects[views_filters_selective][version] = "1.5"
projects[views_ui][version] = "3.18"
projects[wysiwyg][version] = "2.2"

; Themes
projects[bootstrap][version] = "3.19"
projects[adminimal_theme][version] = "1.24"

projects[aesbs337][download][type] = "git"
projects[aesbs337][download][url] = "https://github.com/Coulton7/compseals.git"
projects[aesbs337][type] = "theme"
projects[aesbs337][directory_name] = "bootstrap_component"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

libraries[imagesloaded][download][type] = "get"
libraries[imagesloaded][download][url] = "http://desandro.github.io/imagesloaded/imagesloaded.pkgd.min.js"
libraries[imagesloaded][directory_name] = "imagesloaded"
libraries[imagesloaded][type] = "library"

libraries[masonry][download][type] = "get"
libraries[masonry][download][url] = "https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woocommerce/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.7.2/ckeditor_4.7.2_full.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"
