; This file was auto-generated by drush make
api = 2
core = 7.39
projects[drupal][type] = core

; Modules
projects[views_bulk_operations][version] = “3.4”
projects[backup_migrate][version] = "2.8"
projects[better_exposed_filters][version] = "3.4"
projects[block_class][version] = "2.3"
projects[breadcrumbs_by_path][version] = "1.0-alpha13"
projects[breakpoints][version] = "1.4"
projects[ctools][version] = "1.12"
projects[cdn][version] = "2.10"
projects[contact_forms][version] = "1.8"
projects[facetapi][version] = "1.5"
projects[custom_search][version] = "1.20"
projects[ds][version] = "2.11"
projects[entity][version] = "1.6"
projects[entity2text][version] = "1.0-alpha2"
projects[entity_rules][version] = "1.0-alpha4"
projects[entityform][version] = "2.0-rc1"
projects[entityreference][version] = "1.5"
projects[eu_cookie_compliance][version] = "1.17"
projects[feeds][version] = "2.0-beta1"
projects[feeds_tamper][version] = "1.0-beta4"
projects[fences][version] = "1.2"
projects[field_group_ajaxified_multipage][version] = "1.0-beta2"
projects[field_default_token][version] = "1.3"
projects[field_group][version] = "1.5"
projects[field_hidden][version] = "1.7"
projects[field_slideshow][version] = "1.82+2-dev"
projects[field_validation][version] = "2.3"
projects[filefield_sources][version] = "1.10"
projects[flexslider][version] = "2.0-rc2"
projects[picture][version] = "2.13"
projects[globalredirect][version] = "1.5"
projects[gmap][version] = "2.8"
projects[google_analytics][version] = "2.4"
projects[httpbl][version] = "1.0"
projects[i18n][version] = "1.12"
projects[i18n_contrib][version] = "1.0-alpha2"
projects[i18nviews][version] = "3.x-dev"
projects[job_scheduler][version] = "2.0-alpha3"
projects[jquery_dollar][version] = "1.1"
projects[jquery_update][version] = "3.0-alpha5"
projects[l10n_update][version] = "1.0-beta3"
projects[location][version] = "3.6"
projects[lang_dropdown][version] = "1.5"
projects[libraries][version] = "2.3"
projects[login_security][version] = "1.9"
projects[masonry][version] = "3.0-beta1+4-dev"
projects[masonry_views][version] = "3.0"
projects[oembed][version] = "0.1-beta3"
projects[menu_attributes][version] = "1.0"
projects[menu_block][version] = "2.4"
projects[menu_views][version] = "2.2"
projects[metatag][version] = "1.22”
projects[module_filter][version] = "2.1"
projects[pathauto][version] = "1.3"
projects[pathrules][version] = "1.0"
projects[remote_file_source][version] = "1.0"
projects[remote_stream_wrapper][version] = "1.0-rc1"
projects[rules][version] = "2.10"
projects[rules_url_argument][version] = "1.2"
projects[schema][version] = "1.3"
projects[search_api][version] = "1.22"
projects[search_api_autocomplete][version] = "1.5"
projects[search_api_page][version] = "1.4"
projects[search_api_solr][version] = "1.12"
projects[security_review][version] = "1.2"
projects[taxonomy_menu][version] = "2.0-alpha2"
projects[token][version] = "1.7"
projects[tvi][version] = "1.0-beta3"
projects[variable][version] = "2.3"
projects[views][version] = "3.18"
projects[views_fluid_grid][version] = "3.0"
projects[views_infinite_scroll][version] = "1.2+1-dev"
projects[views_slideshow][version] = “3.9”
projects[wysiwyg][version] = “2.4”
projects[xmlsitemap][version] = "2.3"

; Themes
projects[bootstrap][version] = "2.1"

projects[ember][version] = "2.0-alpha2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[aesseal_classic][download][type] = "git"
projects[aesseal_classic][download][url] = "https://github.com/Coulton7/aesseal_classic.git"
projects[aesseal_classic][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[imagesloaded][download][type] = "git"
libraries[imagesloaded][download][url] = "https://github.com/desandro/imagesloaded.git"
libraries[imagesloaded][directory_name] = "imagesloaded"
libraries[imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[masonry][download][type] = "git"
libraries[masonry][download][url] = "https://github.com/desandro/masonry.git"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[autopager][download][type] = "get"
libraries[autopager][download][url] = "http://jquery-autopager.googlecode.com/files/jquery.autopager-1.0.0.js"
libraries[autopager][directory_name] = "autopager"
libraries[autopager][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woocommerce/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"